function J = calculateResponseSurface(coeffs,azimuths, zeniths)

J = coeffs(1) ...
    + coeffs(2)*azimuths ...
    + coeffs(3)*azimuths.^2 ...
    + coeffs(4)*zeniths ...
    + coeffs(5)*zeniths.^2;

end