function initializeCommandsBus
%% Create the controller output bus automatically
clear busElementData
busElementData = {...
    'wingAngleCommand',1,'double';...
    'stabilizerAngleCommand',1,'double';...
    'rudderAngleCommand',1,'double';...
    'tetherSpeedCommand',1,'double';...
    'radiusOverride',2,'double';...
    'azimuthOverride',2,'double';...
    'zenithOverride',2,'double';...
    'BFXDotOverride',2,'double';...
    'headingOverride',2,'double';...
    'headingDotOverride',2,'double'};
createBusInBaseWorkspace(busElementData,'busControllerOutput')
end