function initializeCommandsBus
%% Create the controller output bus automatically
clear busElementData
busElementData = {...
    'wingAngleCommand',1,'double';...
    'stabilizerAngleCommand',1,'double';...
    'rudderAngleCommand',1,'double';...
    'tetherSpeedCommand',1,'double';...
    'integratorResetBools',6,'boolean';...
    'integratorResetVals',6,'double'};
createBusInBaseWorkspace(busElementData,'busControllerOutput')
end