function h = plotTrustRegion(h,point)
trustRegion = (pi/180)*evalin('base','[ctrl.persistenExcitationAzimuth_deg ctrl.persistenExcitationZenith_deg]');
x = linspace(point(1)-trustRegion(1),point(1)+trustRegion(1),100);
y = linspace(point(2)-trustRegion(2),point(2)+trustRegion(2),100);
x = [x...
    x(end)*ones(size(y))...
    x...
    x(1)*ones(size(y))];
y = [y(end)*ones(size(y))...
    flip(y)...
    y(1)*ones(size(y))...
    y];
z = interp2(h.responseSurface.XData,...
    h.responseSurface.YData,...
    h.responseSurface.ZData,x,y);
h.trustRegion = line(x,y,z);
end